---
title: "Week 4 Activity"
author: 'Group 7: Kyle William Schulz, Moeki Kurita, Yanhan Si'
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Part 1

## 1 Read data

```{r}
path = "./data"
nhanes_demo = sprintf('%s/nhanes_demo.csv', path)
nhanes_ohxden = sprintf('%s/nhanes_ohxden.csv', path)
demo = read_delim(nhanes_demo, delim = ',')
ohxden = read_delim(nhanes_ohxden, delim = ',')
```

## 2 Joining data files

```{r}
nhanes_join = select(ohxden, SEQN, OHDDESTS) %>% 
  left_join(demo, by = 'SEQN')
```

## 3 Cleaning data

```{r}
summary(nhanes_join)
```

```{r}
nhanes_join = nhanes_join %>% 
  transmute(id = SEQN,
            gender = if_else(RIAGENDR == 1,'Male', 'Female'),
            age = RIDAGEYR,
            under_20 = if_else(age < 20, 1, 0),
            college = if_else(DMDEDUC2 == 4 | DMDEDUC2 == 5,
                             'some college/college graduate',
                             'No college/<20', missing = 'No college/<20'),
            exam_status = RIDSTATR,
            ohx_status = OHDDESTS)
nhanes_join
```

## 4 & 5 Create a variable indicating ohx status 

```{r}
nhanes_join = nhanes_join %>% 
  mutate(ohx = if_else(exam_status == 2 & ohx_status == 1,
                      'complete',
                      'missing')) %>% 
  filter(exam_status == 2)
nhanes_join
```

# Part 2

## 1

```{r}
nhanes_join %>% 
  group_by(under_20, ohx) %>%
  summarise(count = n(), .groups = 'drop_last') %>% 
  mutate(prop = count / sum(count))
```

```{r}
nhanes_join %>% 
  group_by(gender, ohx) %>% 
  summarise(count = n(), .groups = 'drop_last') %>% 
  mutate(prop = count / sum(count))
```

```{r}
nhanes_join %>% 
  group_by(college, ohx) %>% 
  summarise(count = n(), .groups = 'drop_last') %>% 
  mutate(prop = count / sum(count))
```